import pyautogui as pg

pg.press("win")
pg.sleep(1)
pg.typewrite("Google")
pg.sleep(1)
pg.press("enter")
pg.sleep(1)
pg.typewrite("youtube.com")
pg.press("enter")
pg.sleep(5)
pg.click(779, 107)
pg.sleep(1)
pg.typewrite("Adalplay")
pg.press("enter")
pg.sleep(5)
pg.click(715, 272)
pg.sleep(5)
pg.click(676, 497)